version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: compose/telegram_bot/Dockerfile
    #environment:
     # - TELEGRAM_BOT_TOKEN=test
    volumes:
      - .:/telegram_bot
    entrypoint: ./entrypoint.sh
    stdin_open: true
    tty: true
    networks:
      - backend

networks:
  backend:
    driver: bridge